# Generated by Django 5.0.6 on 2024-06-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowlingcenter',
            name='name',
            field=models.CharField(default='NONE', max_length=128),
            preserve_default=False,
        ),
    ]
