# Generated by Django 5.0.6 on 2024-06-03 19:54

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0003_alter_league_name_alter_tournament_name'),
        ('profiles', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 19, 54, 12, 922544, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LeagueRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_rosters', to='events.league')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueBowlerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile')),
                ('league_roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_bowler_entries', to='events.leagueroster')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueSidepot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_sidepots', to='events.league')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueBowlerSidepotEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_count', models.PositiveIntegerField(default=1)),
                ('bowler_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_sidepot_entries', to='events.leaguebowlerentry')),
                ('sidepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.leaguesidepot')),
            ],
        ),
        migrations.AddField(
            model_name='leaguebowlerentry',
            name='sidepots',
            field=models.ManyToManyField(related_name='league_bowler_entries', through='events.LeagueBowlerSidepotEntry', to='events.leaguesidepot'),
        ),
    ]
