[tool.djlint]
profile = 'django'
indent = 4
extend_exclude = '.*/vendor/.*,changelog/.*,node_modules/.*,public/.*'
use_gitignore = true
blank_line_after_tag = 'extends,load,endfor,endwith,include'
max_line_length = 120
ignore = 'D018,H005,H006,H019,H023,H029,H030,H031'
sections = [
    'FUTURE',
    'STDLIB',
    'DJANGO',
    'THIRDPARTY',
    'FIRSTPARTY',
    'LOCALFOLDER',
]


# Ruff rules: https://docs.astral.sh/ruff/rules/

[tool.ruff]
extend-exclude = [
    ".*/vendor/.*",
    "changelog/.*",
    "node_modules/.*",
    "public/.*",
]
lint.select = ["F", "E", "W", "I"]
lint.ignore = [
    "D",
    "E722",
    "E713",
    "E401",
    "E402",
    "E501",
    "F841",
    "W191",
    "E111",
    "E114",
    "E117",
]
indent-width = 4
line-length = 120

[tool.ruff.lint.extend-per-file-ignores]
"bowlingmafia/settings/*.py" = ["F401", "F403", "F405"]
"*/__init__.py" = ["F401"]
"*/apps.py" = ["F401"]

[tool.ruff.format]
preview = true
quote-style = "preserve"

[tool.ruff.lint.isort]
section-order = [
    "future",
    "standard-library",
    "django",
    "third-party",
    "first-party",
    "local-folder",
]
known-third-party = ["requests"]

[tool.ruff.lint.isort.sections]
"django" = ["django"]