# Generated by Django 5.0.6 on 2024-06-03 19:54

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eliminator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payout_ratio', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2)])),
                ('allow_multiple_entries', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(default='Eliminator', editable=False, max_length=64)),
                ('reverse', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HandicapEliminator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payout_ratio', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2)])),
                ('allow_multiple_entries', models.BooleanField(default=False, editable=False)),
                ('hdcp_percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('base_average', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('name', models.CharField(default='Handicap Eliminator', editable=False, max_length=64)),
                ('reverse', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HandicapHighGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payout_ratio', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2)])),
                ('allow_multiple_entries', models.BooleanField(default=False, editable=False)),
                ('hdcp_percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('base_average', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('name', models.CharField(default='Handicap High Game Pot', editable=False, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HandicapHighSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payout_ratio', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2)])),
                ('allow_multiple_entries', models.BooleanField(default=False, editable=False)),
                ('hdcp_percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('base_average', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('name', models.CharField(default='Handicap High Series Pot', editable=False, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HandicapMysteryDoubles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payout_ratio', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2)])),
                ('hdcp_percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('base_average', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('name', models.CharField(default='Handicap Mystery Doubles', editable=False, max_length=64)),
                ('allow_multiple_entries', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HandicapWinnerTakeAll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payout_ratio', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2)])),
                ('allow_multiple_entries', models.BooleanField(default=False, editable=False)),
                ('hdcp_percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('base_average', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)])),
                ('name', models.CharField(default='Handicap Winner Take All Pot', editable=False, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HighGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payout_ratio', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2)])),
                ('allow_multiple_entries', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(default='High Game Pot', editable=False, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HighSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payout_ratio', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2)])),
                ('allow_multiple_entries', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(default='High Series Pot', editable=False, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MysteryDoubles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payout_ratio', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2)])),
                ('name', models.CharField(default='Mystery Doubles', editable=False, max_length=64)),
                ('allow_multiple_entries', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WinnerTakeAll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payout_ratio', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2)])),
                ('allow_multiple_entries', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(default='Winner Take All Pot', editable=False, max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
