# Generated by Django 5.0.6 on 2024-06-05 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('profiles', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('bowling_centers', models.ManyToManyField(related_name='%(class)s_bowling_center', to='common.bowlingcenter')),
                ('directors', models.ManyToManyField(related_name='tournament_director', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
