# Generated by Django 5.0.6 on 2024-06-05 03:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('profiles', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField()),
                ('admins', models.ManyToManyField(related_name='league_admin', to='profiles.profile')),
                ('bowling_centers', models.ManyToManyField(related_name='%(class)s_bowling_center', to='common.bowlingcenter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeagueSidepot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_sidepots', to='leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='BowlerSidepotEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_count', models.PositiveIntegerField(default=1)),
                ('sidepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.leaguesidepot')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_rosters', to='leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_bowler', to='profiles.profile')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_roster_entries', to='leagues.roster')),
                ('sidepots', models.ManyToManyField(related_name='league_bowler_sidepot_entries', through='leagues.BowlerSidepotEntry', to='leagues.leaguesidepot')),
            ],
        ),
        migrations.AddField(
            model_name='bowlersidepotentry',
            name='bowler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.rosterentry'),
        ),
    ]
