# Generated by Django 5.0.6 on 2024-06-05 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_alter_league_bowling_centers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowlersidepotentry',
            name='bowler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_bowler_entries', to='leagues.rosterentry'),
        ),
    ]
