# Generated by Django 5.0.6 on 2024-06-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_alter_bowlersidepotentry_bowler_alter_game_bowler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguesidepot',
            name='base_avg',
        ),
        migrations.RemoveField(
            model_name='leaguesidepot',
            name='hdcp_pct',
        ),
    ]
