# Generated by Django 5.0.6 on 2024-06-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_remove_leaguesidepot_base_avg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguesidepot',
            old_name='reverse_sidepot',
            new_name='is_reverse',
        ),
    ]
