# Generated by Django 5.0.6 on 2024-06-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_rename_reverse_sidepot_leaguesidepot_is_reverse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguesidepot',
            old_name='name',
            new_name='type',
        ),
    ]
