# Generated by Django 5.0.6 on 2024-06-15 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_rename_name_leaguesidepot_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='LeagueGame',
        ),
    ]
