# Generated by Django 5.0.6 on 2024-06-20 23:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_league_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguesidepot',
            name='games_used',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
    ]
