# Generated by Django 5.0.6 on 2024-06-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_alter_leaguesidepot_games_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguesidepot',
            name='is_reverse',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
