# Generated by Django 5.0.6 on 2024-06-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_roster_is_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
