# Generated by Django 5.0.6 on 2024-06-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_league_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowlersidepotentry',
            name='entry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
